controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    annotations:
      ske.sotoon.ir/allocate-ip: external
  resources:
    requests:
      cpu: "300m"
      memory: "256Mi"
    limits:
      cpu: "600m"
      memory: "512Mi"
  metrics:
    enabled: true